#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#
# Event nethserver-ipsec-tunnels-update
#
event_actions('nethserver-ipsec-tunnels-update', qw( 
    initialize-default-databases 00
));

event_templates('nethserver-ipsec-tunnels-update', qw(
    /etc/ipsec.d/tunnels.conf
    /etc/ipsec.d/tunnels.secrets
));

event_services('nethserver-ipsec-tunnels-update', qw(
    ipsec restart
));

#
# Event nethserver-ipsec-tunnels-save
#
event_templates('nethserver-ipsec-tunnels-save', qw(
    /etc/ipsec.d/tunnels.conf
    /etc/ipsec.d/tunnels.secrets
));

event_services('nethserver-ipsec-tunnels-save', qw(
    ipsec restart
));

event_actions('nethserver-ipsec-tunnels-save', qw(
    trusted-networks-modify 95
));

#
# Event interface-update
#

event_templates('interface-update', qw(
    /etc/ipsec.d/tunnels.conf
));

event_services('interface-update', qw(
    ipsec restart
));

#
# Event nethserver-ipsec-tunnels-modify
#
event_templates('nethserver-ipsec-tunnels-modify', qw(
    /etc/ipsec.d/tunnels.conf
));

event_actions('nethserver-ipsec-tunnels-modify', qw(
    nethserver-ipsec-tunnels-edit 40
));

