#!/usr/bin/perl
#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Delete conntrack connection on ipsec service stop for disabled vpn
#

use warnings;
use strict;

use esmith::NetworksDB;
my $vdb = esmith::NetworksDB->open_ro('vpn');

foreach my $tunnel ($vdb->get_all_by_prop('type' => 'ipsec-tunnel')) {
    my $status = $tunnel->prop('status') || 'disabled';
    next if ($status eq 'enabled');
    next if (!defined($tunnel->prop('right')));
    system("/usr/sbin/conntrack","-D","-d",$tunnel->prop('right'),"--proto","UDP","--sport","500","--dport","500","2>/dev/null");
    system("/usr/sbin/conntrack","-D","-d",$tunnel->prop('right'),"--proto","UDP","--sport","4500","--dport","4500","2>/dev/null");
}
