#!/bin/bash
#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

event=$1
action=$2
tunnel="${3}_ipsec-tunnel"
remoteIP=$4

if [ -z "$event" ]; then
    exit 0
fi

if [ "$action" == "create" ]; then
    /usr/sbin/ipsec auto --start "$tunnel"
elif [ "$action" == "modify" ]; then
    /usr/sbin/ipsec auto --delete "$tunnel"
    /usr/sbin/ipsec auto --start "$tunnel"
elif [ "$action" == "delete" ]; then
    /usr/sbin/ipsec auto --delete "$tunnel"
    ret=$?

    if [ ! -z "$remoteIP" ]; then
        /usr/sbin/conntrack -D  -d  $remoteIP --proto UDP --sport 500 --dport 500 2>/dev/null
        /usr/sbin/conntrack -D  -d  $remoteIP --proto UDP --sport 4500 --dport 4500 2>/dev/null
    fi

    exit $ret
fi
